CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS card_db;

CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'app1234';
GRANT ALL PRIVILEGES ON card_db.* TO 'app'@'%';

CREATE USER IF NOT EXISTS 'app_ro'@'%' IDENTIFIED BY 'app_ro_pw';
GRANT SELECT ON card_db.* TO 'app_ro'@'%';

FLUSH PRIVILEGES;